CREATE TABLE IF NOT EXISTS website_config (
    Revision INTEGER PRIMARY KEY AUTOINCREMENT,
    FA_TOKEN_A TEXT DEFAULT "",
    FA_TOKEN_B TEXT DEFAULT "",
    BLUESKY_HANDLE TEXT DEFAULT "",
    BLUESKY_PASSWORD TEXT DEFAULT ""
);